#############################################################################
# Makefile for building: Program1
# Generated by qmake (3.0) (Qt 5.4.1)
# Project:  Program1.pro
# Template: app
# Command: /home/xavier/Qt/5.4/gcc/bin/qmake -spec linux-g++ -o Makefile Program1.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIE $(DEFINES)
CXXFLAGS      = -pipe -O2 -O3 -msse4.1 -mssse3 -msse3 -msse2 -msse -llapack -lblas -lf2c -Wall -W -D_REENTRANT -fPIE $(DEFINES)
INCPATH       = -I. -I/usr/lib/i386-linux-gnu -I/usr/local/include/opencv -I../../../NVIDIA_GPU_Computing_SDK/OpenCL/common/inc -I../../../NVIDIA_GPU_Computing_SDK/shared/inc -I../../../Qt/5.4/gcc/include -I../../../Qt/5.4/gcc/include/QtCore -I. -I../../../Qt/5.4/gcc/mkspecs/linux-g++
QMAKE         = /home/xavier/Qt/5.4/gcc/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Program11.0.0
DISTDIR = /home/xavier/Bureau/Developpement/OpenCL_Flow/.tmp/Program11.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/home/xavier/Qt/5.4/gcc -Wl,-rpath,/home/xavier/Qt/5.4/gcc/lib
LIBS          = $(SUBLIBS) -L/usr/lib/i386-linux-gnu -lGL -lGLU -lglut -llapack -lblas -lgfortran -L /home/xavier/NVIDIA_GPU_Computing_SDK/C/common/lib/linux -lGLEW -L/usr/local/lib -lm -lopencv_core -lopencv_imgproc -lopencv_highgui -lopencv_objdetect -lopencv_calib3d -L/home/xavier/NVIDIA_GPU_Computing_SDK/shared/lib -lshrutil_i386 -lOpenCL -L/home/xavier/NVIDIA_GPU_Computing_SDK/OpenCL/common/lib -loclUtil_i386 -L/home/xavier/Qt/5.4/gcc/lib -lQt5Core -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = flowGL.cpp \
		oclFlow.cpp 
OBJECTS       = flowGL.o \
		oclFlow.o
DIST          = ../../../Qt/5.4/gcc/mkspecs/features/spec_pre.prf \
		../../../Qt/5.4/gcc/mkspecs/common/shell-unix.conf \
		../../../Qt/5.4/gcc/mkspecs/common/unix.conf \
		../../../Qt/5.4/gcc/mkspecs/common/linux.conf \
		../../../Qt/5.4/gcc/mkspecs/common/gcc-base.conf \
		../../../Qt/5.4/gcc/mkspecs/common/gcc-base-unix.conf \
		../../../Qt/5.4/gcc/mkspecs/common/g++-base.conf \
		../../../Qt/5.4/gcc/mkspecs/common/g++-unix.conf \
		../../../Qt/5.4/gcc/mkspecs/qconfig.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_core.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_declarative.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_declarative_private.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_enginio.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_enginio_private.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_help.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_location.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_location_private.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_network.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_script.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_script_private.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_webengine.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_webkit.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_webview.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_x11extras.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt/5.4/gcc/mkspecs/features/qt_functions.prf \
		../../../Qt/5.4/gcc/mkspecs/features/qt_config.prf \
		../../../Qt/5.4/gcc/mkspecs/linux-g++/qmake.conf \
		../../../Qt/5.4/gcc/mkspecs/features/spec_post.prf \
		../../../Qt/5.4/gcc/mkspecs/features/exclusive_builds.prf \
		../../../Qt/5.4/gcc/mkspecs/features/default_pre.prf \
		../../../Qt/5.4/gcc/mkspecs/features/resolve_config.prf \
		../../../Qt/5.4/gcc/mkspecs/features/default_post.prf \
		../../../Qt/5.4/gcc/mkspecs/features/warn_on.prf \
		../../../Qt/5.4/gcc/mkspecs/features/qt.prf \
		../../../Qt/5.4/gcc/mkspecs/features/resources.prf \
		../../../Qt/5.4/gcc/mkspecs/features/moc.prf \
		../../../Qt/5.4/gcc/mkspecs/features/unix/thread.prf \
		../../../Qt/5.4/gcc/mkspecs/features/testcase_targets.prf \
		../../../Qt/5.4/gcc/mkspecs/features/exceptions.prf \
		../../../Qt/5.4/gcc/mkspecs/features/yacc.prf \
		../../../Qt/5.4/gcc/mkspecs/features/lex.prf \
		Program1.pro  flowGL.cpp \
		oclFlow.cpp
QMAKE_TARGET  = Program1
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = Program1


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Program1.pro ../../../Qt/5.4/gcc/mkspecs/linux-g++/qmake.conf ../../../Qt/5.4/gcc/mkspecs/features/spec_pre.prf \
		../../../Qt/5.4/gcc/mkspecs/common/shell-unix.conf \
		../../../Qt/5.4/gcc/mkspecs/common/unix.conf \
		../../../Qt/5.4/gcc/mkspecs/common/linux.conf \
		../../../Qt/5.4/gcc/mkspecs/common/gcc-base.conf \
		../../../Qt/5.4/gcc/mkspecs/common/gcc-base-unix.conf \
		../../../Qt/5.4/gcc/mkspecs/common/g++-base.conf \
		../../../Qt/5.4/gcc/mkspecs/common/g++-unix.conf \
		../../../Qt/5.4/gcc/mkspecs/qconfig.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_core.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_declarative.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_declarative_private.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_enginio.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_enginio_private.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_help.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_location.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_location_private.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_network.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_script.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_script_private.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_webengine.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_webkit.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_webview.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_x11extras.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt/5.4/gcc/mkspecs/features/qt_functions.prf \
		../../../Qt/5.4/gcc/mkspecs/features/qt_config.prf \
		../../../Qt/5.4/gcc/mkspecs/linux-g++/qmake.conf \
		../../../Qt/5.4/gcc/mkspecs/features/spec_post.prf \
		../../../Qt/5.4/gcc/mkspecs/features/exclusive_builds.prf \
		../../../Qt/5.4/gcc/mkspecs/features/default_pre.prf \
		../../../Qt/5.4/gcc/mkspecs/features/resolve_config.prf \
		../../../Qt/5.4/gcc/mkspecs/features/default_post.prf \
		../../../Qt/5.4/gcc/mkspecs/features/warn_on.prf \
		../../../Qt/5.4/gcc/mkspecs/features/qt.prf \
		../../../Qt/5.4/gcc/mkspecs/features/resources.prf \
		../../../Qt/5.4/gcc/mkspecs/features/moc.prf \
		../../../Qt/5.4/gcc/mkspecs/features/unix/thread.prf \
		../../../Qt/5.4/gcc/mkspecs/features/testcase_targets.prf \
		../../../Qt/5.4/gcc/mkspecs/features/exceptions.prf \
		../../../Qt/5.4/gcc/mkspecs/features/yacc.prf \
		../../../Qt/5.4/gcc/mkspecs/features/lex.prf \
		Program1.pro \
		/home/xavier/Qt/5.4/gcc/lib/libQt5Core.prl
	$(QMAKE) -spec linux-g++ -o Makefile Program1.pro
../../../Qt/5.4/gcc/mkspecs/features/spec_pre.prf:
../../../Qt/5.4/gcc/mkspecs/common/shell-unix.conf:
../../../Qt/5.4/gcc/mkspecs/common/unix.conf:
../../../Qt/5.4/gcc/mkspecs/common/linux.conf:
../../../Qt/5.4/gcc/mkspecs/common/gcc-base.conf:
../../../Qt/5.4/gcc/mkspecs/common/gcc-base-unix.conf:
../../../Qt/5.4/gcc/mkspecs/common/g++-base.conf:
../../../Qt/5.4/gcc/mkspecs/common/g++-unix.conf:
../../../Qt/5.4/gcc/mkspecs/qconfig.pri:
../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_bluetooth.pri:
../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_clucene_private.pri:
../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_concurrent.pri:
../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_core.pri:
../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_core_private.pri:
../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_dbus.pri:
../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_dbus_private.pri:
../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_declarative.pri:
../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_declarative_private.pri:
../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_designer.pri:
../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_designer_private.pri:
../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_enginio.pri:
../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_enginio_private.pri:
../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_gui.pri:
../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_gui_private.pri:
../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_help.pri:
../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_help_private.pri:
../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_location.pri:
../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_location_private.pri:
../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_multimedia.pri:
../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_network.pri:
../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_network_private.pri:
../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_nfc.pri:
../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_nfc_private.pri:
../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_opengl.pri:
../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_opengl_private.pri:
../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_openglextensions.pri:
../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_positioning.pri:
../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_positioning_private.pri:
../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_printsupport.pri:
../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_qml.pri:
../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_qml_private.pri:
../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_qmltest.pri:
../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_quick.pri:
../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_quick_private.pri:
../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_script.pri:
../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_script_private.pri:
../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_scripttools.pri:
../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_sensors.pri:
../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_sensors_private.pri:
../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_serialport.pri:
../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_serialport_private.pri:
../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_sql.pri:
../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_sql_private.pri:
../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_svg.pri:
../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_svg_private.pri:
../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_testlib.pri:
../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_testlib_private.pri:
../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_uitools.pri:
../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_uitools_private.pri:
../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_webchannel.pri:
../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_webengine.pri:
../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_webengine_private.pri:
../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_webenginecore.pri:
../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_webkit.pri:
../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_webkit_private.pri:
../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_websockets.pri:
../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_websockets_private.pri:
../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_webview.pri:
../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_webview_private.pri:
../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_widgets.pri:
../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_widgets_private.pri:
../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_x11extras.pri:
../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_x11extras_private.pri:
../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_xml.pri:
../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_xml_private.pri:
../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../Qt/5.4/gcc/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../Qt/5.4/gcc/mkspecs/features/qt_functions.prf:
../../../Qt/5.4/gcc/mkspecs/features/qt_config.prf:
../../../Qt/5.4/gcc/mkspecs/linux-g++/qmake.conf:
../../../Qt/5.4/gcc/mkspecs/features/spec_post.prf:
../../../Qt/5.4/gcc/mkspecs/features/exclusive_builds.prf:
../../../Qt/5.4/gcc/mkspecs/features/default_pre.prf:
../../../Qt/5.4/gcc/mkspecs/features/resolve_config.prf:
../../../Qt/5.4/gcc/mkspecs/features/default_post.prf:
../../../Qt/5.4/gcc/mkspecs/features/warn_on.prf:
../../../Qt/5.4/gcc/mkspecs/features/qt.prf:
../../../Qt/5.4/gcc/mkspecs/features/resources.prf:
../../../Qt/5.4/gcc/mkspecs/features/moc.prf:
../../../Qt/5.4/gcc/mkspecs/features/unix/thread.prf:
../../../Qt/5.4/gcc/mkspecs/features/testcase_targets.prf:
../../../Qt/5.4/gcc/mkspecs/features/exceptions.prf:
../../../Qt/5.4/gcc/mkspecs/features/yacc.prf:
../../../Qt/5.4/gcc/mkspecs/features/lex.prf:
Program1.pro:
/home/xavier/Qt/5.4/gcc/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -spec linux-g++ -o Makefile Program1.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents flowGL.cpp oclFlow.cpp $(DISTDIR)/


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

flowGL.o: flowGL.cpp ../../../NVIDIA_GPU_Computing_SDK/OpenCL/common/inc/oclUtils.h \
		../../../NVIDIA_GPU_Computing_SDK/shared/inc/shrUtils.h \
		../../../NVIDIA_GPU_Computing_SDK/OpenCL/common/inc/CL/opencl.h \
		../../../NVIDIA_GPU_Computing_SDK/OpenCL/common/inc/CL/cl.h \
		../../../NVIDIA_GPU_Computing_SDK/OpenCL/common/inc/CL/cl_platform.h \
		../../../NVIDIA_GPU_Computing_SDK/OpenCL/common/inc/CL/cl_gl.h \
		../../../NVIDIA_GPU_Computing_SDK/OpenCL/common/inc/CL/cl_gl_ext.h \
		../../../NVIDIA_GPU_Computing_SDK/OpenCL/common/inc/CL/cl_ext.h \
		../../../NVIDIA_GPU_Computing_SDK/shared/inc/GL/glew.h \
		../../../NVIDIA_GPU_Computing_SDK/shared/inc/GL/glu.h \
		../../../NVIDIA_GPU_Computing_SDK/shared/inc/GL/gl.h \
		../../../NVIDIA_GPU_Computing_SDK/shared/inc/GL/glext.h \
		../../../NVIDIA_GPU_Computing_SDK/shared/inc/GL/freeglut.h \
		../../../NVIDIA_GPU_Computing_SDK/shared/inc/GL/freeglut_std.h \
		../../../NVIDIA_GPU_Computing_SDK/shared/inc/GL/freeglut_ext.h \
		/usr/local/include/opencv/cv.h \
		/usr/local/include/opencv/highgui.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o flowGL.o flowGL.cpp

oclFlow.o: oclFlow.cpp ../../../NVIDIA_GPU_Computing_SDK/OpenCL/common/inc/CL/cl.h \
		../../../NVIDIA_GPU_Computing_SDK/OpenCL/common/inc/CL/cl_platform.h \
		../../../NVIDIA_GPU_Computing_SDK/shared/inc/shrUtils.h \
		../../../NVIDIA_GPU_Computing_SDK/OpenCL/common/inc/oclUtils.h \
		../../../NVIDIA_GPU_Computing_SDK/OpenCL/common/inc/CL/opencl.h \
		../../../NVIDIA_GPU_Computing_SDK/OpenCL/common/inc/CL/cl_gl.h \
		../../../NVIDIA_GPU_Computing_SDK/OpenCL/common/inc/CL/cl_gl_ext.h \
		../../../NVIDIA_GPU_Computing_SDK/OpenCL/common/inc/CL/cl_ext.h \
		../../../NVIDIA_GPU_Computing_SDK/shared/inc/GL/gl.h \
		../../../NVIDIA_GPU_Computing_SDK/shared/inc/GL/glext.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o oclFlow.o oclFlow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

